---
language: ruby
script: bin/rspec
rvm:
  - 2.1
  - 2.2
branches:
  only:
    - master
builder_args: --jobs 7
notifications:
  irc:
    channels:
      - 'chat.freenode.net#bloomberg'
    use_notice: true
    skip_join: true
    template:
      - "%{message} (%{author}): %{build_url}"
matrix:
  fast_finish: true
